env:
  - DBNAME='variation' DBUSER='variation' DBPASS='variation'
services:
  - postgresql
before_script:
  - psql -c "create user $DBUSER password '$DBPASS'" -U postgres
  - psql -c "CREATE DATABASE $DBNAME WITH ENCODING='UTF8' owner=$DBUSER" -U postgres
  - PGPASSWORD=$DBPASS psql $DBNAME -c "CREATE SCHEMA pgcrypto AUTHORIZATION $DBUSER;"
  - psql $DBNAME -c "CREATE EXTENSION pgcrypto WITH SCHEMA pgcrypto;" -U postgres
  - bash ./install.sh
  - bash ./update.sh
  - echo "<?php \$pg_host = 'localhost'; \$pg_user = '$DBUSER'; \$pg_pass = '$DBPASS'; \$pg_database = '$DBNAME';" > config.inc.php

language: php
php:
  - '5.5'
script:
  - bash ./run-tests.sh

before_deploy:
  - (cd data && php mecs.php) && pg_dump -U postgres -w $DBNAME | gzip > dump.db.gz && ls -l dump.db.gz

deploy:
  provider: script
  script: ls
  on:
    branch: master
