env:
  - DBNAME='travis_ci_test' DBUSER='tester' DBPASS='tester'
services:
  - postgresql
before_script:
  - psql -c "create user tester password 'tester'" -U postgres
  - psql -c "CREATE DATABASE travis_ci_test WITH ENCODING='UTF8' owner=tester" -U postgres
  - PGPASSWORD=$DBPASS psql $DBNAME -c "CREATE SCHEMA pgcrypto AUTHORIZATION $DBUSER;"
  - psql $DBNAME -c "CREATE EXTENSION pgcrypto WITH SCHEMA pgcrypto;" -U postgres
  - bash ./install.sh
  - bash ./update.sh
  - echo "<?php \$pg_host = 'localhost'; \$pg_user = '$DBUSER'; \$pg_pass = '$DBPASS'; \$pg_database = '$DBNAME';" > config.inc.php

language: php
php:
  - '5.5'
script:
  - bash ./run-tests.sh

before_deploy:
  - pg_dump -U postgres -w $DBNAME > dump.db && ls -l dump.db

deploy:
  provider: script
  script: ls
  on:
    branch: master
